name: Release EOC Beta Chart

on:
  push:
    branches:
      - eoc-2.0.0-beta.1

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Chart | Push
        uses: appany/helm-oci-chart-releaser@v0.5.0
        with:
          name: eoc
          repository: radiantlogic-devops/helm-charts
          path: charts/eoc
          tag: 2.0.0-beta.1
          registry: ghcr.io
          registry_username: "$GITHUB_ACTOR"
          registry_password: ${{ secrets.GITHUB_TOKEN }}
